language: scala
scala:
   - 2.11.8
   - 2.12.1
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - remove_dir_from_path $JAVA_HOME/bin
  - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
